FROM python:3.10.13-bookworm

WORKDIR /root/code

# Install dependencies

RUN pip3 install --upgrade pip
RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install Flask==3.0.1

# Copy the entire project to the working directory
COPY ./code /root/code  

# CMD tail -f /dev/null
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]



